### ISSUE TITLE
Implementing wall that is thinner than 1 cell

### ISSUE THREAD

**Issue by crinny** [brean/python-pathfinding#29]
I need to implement A* pathfinding algorithm on the following map (don't mind the * labels):
![image](https://user-images.githubusercontent.com/42045258/76444017-6233cd00-63d4-11ea-88b6-a12cace3de83.png)
As you can see, the wall isn't taking full cell and I need to implement the same using this library

**Comment by brean** [comment]
Hi Nikita, 

you can do this by storing the walls inside the nodes themself (maybe as booleans for north/south/east/west, if the boolean is False there is a wall, set it to True as default if it is walkable) and then create your own Grid-implementation (I would inherit from https://github.com/brean/python-pathfinding/blob/master/pathfinding/core/grid.py) that returns neighbours only if of the flag is True. You probably want to create the nodes manually then instead of using a for-loop to create them from a matrix (see build_nodes-function) or invent some own data format that also encodes the walls.

I will close this issue for now but feel free to reopen it if you are having problems implementing it or did not understand my suggestion.
