### ISSUE TITLE
Get The Closest Cell In Case Of No Direct Path

### ISSUE THREAD

**Issue by RaJiska** [brean/python-pathfinding#31]
Hello,

I'd like to know if there is a way to get the closest cell to the destination in case there is no direct path to it.
if not, is there a way to implement it myself without spending too long working on it ? 

Thanks.

**Comment by brean** [comment]
The problem is how the closest cell is defined. Easiest heuristic that comes to my mind is this:
1. take all cells within a minimum radius from the end
2. if you did not find a cell within that radius that is free extend the radius and continue
3. if you found a cell that is free use that cell as end of the pathfinding algorithm.

The problem is that it is impossible to tell if there is a way, it might be that the goal is just behind a very large wall with a very small opening, so if there is no path the algorithm might run until it has checked every field on the map. You can try to break after a certain amount of iterations and then try to run the algorithm with the heuristic I just mentioned or you could always try to stop if you reached a certain destination close to the goal but then you will never reach the goal directly.

Depending on your application you might want to mix this with other algorithms. In robotics for example you would use A* pathfinding as global planner to get close to your goal and use a local planner to plan the exact trajectory that considers the exact shape of your robot, (see https://wiki.ros.org/dwa_local_planner )

**Comment by RaJiska** [comment]
Thank you very much for your help, this is more than enough for me to get started.
